[package]
name = "textool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.8", features = ["derive"] }
image = "0.24.6"
jmmt = { path = "../jmmt" }

# Temporary, until the reader code is thrown into jmmt crate
binext = "1.0.0"
